default: &default
  adapter: postgresql
  encoding: unicode
  pool: 20
  host: localhost

development:
  <<: *default
  database: shvedbot_development
  username: postgres
  password: shved

test:
  <<: *default
  database: shvedbot_test
  username: postgres
  password: shved

